-- ============================================================
-- SUPABASE SCHEMA FOR TRADING BOT
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- ============================================================

-- =============================================
-- TABLE 1: signals
-- Replaces Google Sheets "Signals" tab
-- Stores every signal generated by the bot
-- =============================================
CREATE TABLE IF NOT EXISTS signals (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  engine_version TEXT,
  engine_mode TEXT,
  spot_price NUMERIC,
  atm_strike NUMERIC,
  vix NUMERIC,
  volume_ratio NUMERIC,
  session_progress NUMERIC,
  rsi NUMERIC,
  macd NUMERIC,
  macd_flip TEXT,
  momentum NUMERIC,
  adx NUMERIC,
  super_trend TEXT,
  volatility_atr NUMERIC,
  put_call_ratio NUMERIC,
  writers_zone TEXT,
  writers_confidence NUMERIC,
  gamma_exposure NUMERIC,
  "Gamma_Flip Level" NUMERIC,
  "GEX_Regime" TEXT,
  iv_skew NUMERIC,
  "IV_skew_bias" TEXT,
  poc_distance NUMERIC,
  candle_pattern TEXT,
  price_action_score NUMERIC,
  market_strength NUMERIC,
  regime TEXT,
  raw_signal TEXT,
  signal TEXT,
  confidence NUMERIC,
  ai_insights TEXT,
  reason TEXT,
  blocked_reason TEXT,
  streak_count INTEGER,
  "LastSignal" TEXT,
  "LastFireTime" TIMESTAMPTZ
);

-- =============================================
-- TABLE 2: active_exit_orders
-- Replaces Google Sheets "Active_Exit_Orders" tab
-- Tracks SL and Target orders for each trade
-- =============================================
CREATE TABLE IF NOT EXISTS active_exit_orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  entry_order_id TEXT NOT NULL UNIQUE,
  sl_order_id TEXT,
  target_order_id TEXT,
  symbol TEXT NOT NULL,
  entry_price NUMERIC(10,2),
  sl_price NUMERIC(10,2),
  target_price NUMERIC(10,2),
  quantity INTEGER,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'ACTIVE',
  risk_reward_ratio NUMERIC(6,2),
  
  -- Exit Details
  exit_type TEXT,
  exit_price NUMERIC(10,2),
  pnl NUMERIC(12,2),
  exit_timestamp TIMESTAMPTZ,
  
  -- Institutional Metadata
  security_id TEXT,
  max_loss NUMERIC(12,2),
  max_profit NUMERIC(12,2),
  actual_rr NUMERIC(8,2),
  execution_time TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- TABLE 3: trades
-- Replaces Google Sheets "Trades" tab
-- Complete trade lifecycle tracking
-- =============================================
CREATE TABLE IF NOT EXISTS trades (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  entry_order_id TEXT NOT NULL UNIQUE,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  symbol TEXT NOT NULL,
  entry_price NUMERIC(10,2),
  stop_loss NUMERIC(10,2),
  target NUMERIC(10,2),
  quantity INTEGER,
  status TEXT DEFAULT 'ACTIVE',
  signal TEXT,
  confidence NUMERIC(10,4),
  risk_reward_ratio NUMERIC(6,2),
  
  -- Exit Results
  exit_price NUMERIC(10,2),
  pnl NUMERIC(12,2),
  exit_type TEXT,
  exit_timestamp TIMESTAMPTZ,
  
  -- Performance Metrics
  max_loss NUMERIC(12,2),
  max_profit NUMERIC(12,2),
  actual_rr NUMERIC(8,2),
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- INDEXES for fast lookups
-- This is the main advantage over Google Sheets!
-- =============================================

-- Signals: query by timestamp for ML training data
CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON signals(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signals_signal ON signals(signal);

-- Active Exit Orders: the monitor queries this every 2 minutes
CREATE INDEX IF NOT EXISTS idx_exit_orders_status ON active_exit_orders(status);
CREATE INDEX IF NOT EXISTS idx_exit_orders_entry_id ON active_exit_orders(entry_order_id);

-- Trades: query by status and lookup by entry_order_id
CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_entry_id ON trades(entry_order_id);
CREATE INDEX IF NOT EXISTS idx_trades_timestamp ON trades(timestamp DESC);

-- =============================================
-- ROW LEVEL SECURITY (RLS)
-- Enable RLS but allow service_role full access
-- =============================================
ALTER TABLE signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE active_exit_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;

-- Allow service_role (used by n8n) to do everything
CREATE POLICY "Service role full access on signals" ON signals
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access on active_exit_orders" ON active_exit_orders
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access on trades" ON trades
  FOR ALL USING (true) WITH CHECK (true);

-- =============================================
-- USEFUL VIEWS for AI Model Training
-- =============================================

-- View: Get all completed trades with P&L
CREATE OR REPLACE VIEW completed_trades_summary AS
SELECT 
  t.entry_order_id,
  t.symbol,
  t.signal,
  t.entry_price,
  t.exit_price,
  t.pnl,
  t.exit_type,
  t.confidence,
  t.risk_reward_ratio,
  t.timestamp AS entry_time,
  t.exit_timestamp AS exit_time,
  EXTRACT(EPOCH FROM (t.exit_timestamp - t.timestamp)) / 60 AS duration_minutes
FROM trades t
WHERE t.status = 'CLOSED'
ORDER BY t.timestamp DESC;

-- View: Daily P&L summary
CREATE OR REPLACE VIEW daily_pnl_summary AS
SELECT 
  DATE(timestamp) AS trade_date,
  COUNT(*) AS total_trades,
  SUM(CASE WHEN pnl > 0 THEN 1 ELSE 0 END) AS winning_trades,
  SUM(CASE WHEN pnl <= 0 THEN 1 ELSE 0 END) AS losing_trades,
  ROUND(SUM(pnl)::NUMERIC, 2) AS total_pnl,
  ROUND(AVG(pnl)::NUMERIC, 2) AS avg_pnl,
  ROUND(MAX(pnl)::NUMERIC, 2) AS best_trade,
  ROUND(MIN(pnl)::NUMERIC, 2) AS worst_trade
FROM trades
WHERE status = 'CLOSED'
GROUP BY DATE(timestamp)
ORDER BY trade_date DESC;

-- View: Signal accuracy analysis (for model tuning)
CREATE OR REPLACE VIEW signal_accuracy AS
SELECT 
  s.signal,
  COUNT(*) AS total_signals,
  ROUND(AVG(s.confidence)::NUMERIC, 4) AS avg_confidence,
  ROUND(AVG(s.rsi)::NUMERIC, 2) AS avg_rsi,
  ROUND(AVG(s.vix)::NUMERIC, 2) AS avg_vix,
  ROUND(AVG(s.market_strength)::NUMERIC, 2) AS avg_market_strength
FROM signals s
GROUP BY s.signal
ORDER BY total_signals DESC;
