-- ============================================================
-- SUPABASE SCHEMA FOR TRADING BOT
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- ============================================================

-- =============================================
-- TABLE 1: signals
-- Replaces Google Sheets "Signals" tab
-- Stores every signal generated by the bot
-- Version: 5.0 | Captures ALL 59 API output fields
-- =============================================
CREATE TABLE IF NOT EXISTS signals (
  -- ── Meta ──────────────────────────────────────────────────
  id                      UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
  timestamp               TIMESTAMPTZ   DEFAULT NOW(),
  created_at              TIMESTAMPTZ   DEFAULT NOW(),
  session_date            TEXT,                          -- e.g. "2026-03-24"
  engine_version          TEXT,                          -- "v4.0_AI_Ensemble"
  engine_mode             TEXT,                          -- "AI_ENSEMBLE" | "RULES_FALLBACK"
  processing_time_ms      NUMERIC,                       -- API response time in ms

  -- ── Market Data (Raw Inputs) ───────────────────────────────
  spot_price              NUMERIC,                       -- NIFTY LTP
  atm_strike              NUMERIC,                       -- ATM strike rounded to 50
  vix                     NUMERIC,                       -- India VIX
  vix_multiplier          NUMERIC       DEFAULT 1.0,     -- VIX scaling factor applied
  combined_multiplier     NUMERIC       DEFAULT 1.0,     -- vix × exhaustion multiplier

  -- ── Core Signal Output ────────────────────────────────────
  signal                  TEXT,                          -- BUY CALL (CE)/BUY PUT (PE)/WAIT/AVOID/SIDEWAYS/MARKET_CLOSED
  raw_signal              TEXT,                          -- Pre-filter direction
  confidence              NUMERIC,                       -- Score / AI probability %
  blocked_reason          TEXT,                          -- Why signal was blocked
  regime                  TEXT,                          -- STRONG_BULLISH/BEARISH_TREND/SIDEWAYS_RANGING etc.
  reason                  TEXT,                          -- Human readable scoring reason
  ai_insights             TEXT,                          -- AI key features or rule insights (joined)

  -- ── Streak & Repeat Protection ────────────────────────────
  streak_count            INTEGER       DEFAULT 0,
  streak_confirmed        BOOLEAN       DEFAULT FALSE,
  last_signal             TEXT,                          -- Previous fired signal direction
  last_fire_time          TIMESTAMPTZ,                   -- When last actual CE/PE fired

  -- ── Trend Indicators ──────────────────────────────────────
  adx                     NUMERIC,                       -- ADX value (0-100)
  plus_di                 NUMERIC,                       -- +DI line
  minus_di                NUMERIC,                       -- -DI line
  ema20_distance          NUMERIC,                       -- % distance LTP vs EMA20
  super_trend             TEXT,                          -- "Bullish" | "Bearish" | "Neutral"
  supertrend_validated    BOOLEAN       DEFAULT FALSE,   -- True if EMA20+PSAR agree

  -- ── MACD ──────────────────────────────────────────────────
  macd                    NUMERIC,                       -- Raw MACD line value
  macd_flip               TEXT,                          -- "BULLISH_FLIP" | "BEARISH_FLIP" | "NONE"
  macd_status             TEXT,                          -- "Bullish" | "Bearish" | "Neutral"
  momentum                NUMERIC,                       -- MACD histogram value

  -- ── Momentum Indicators ───────────────────────────────────
  rsi                     NUMERIC,                       -- RSI(14)
  stochastic              NUMERIC,                       -- Stochastic %K
  cci                     NUMERIC,                       -- CCI(20)
  mfi                     NUMERIC,                       -- Money Flow Index(14)

  -- ── Volatility Indicators ─────────────────────────────────
  volatility_atr          NUMERIC,                       -- ATR(14) Wilder smoothed
  bb_width                NUMERIC,                       -- Bollinger Band width %

  -- ── Volume ────────────────────────────────────────────────
  volume_ratio            NUMERIC,                       -- Latest vol / 20-bar avg vol
  session_progress        NUMERIC,                       -- % of trading day elapsed (0-100)

  -- ── Options / Writers Zone ────────────────────────────────
  put_call_ratio          NUMERIC,                       -- PCR by Open Interest
  put_call_premium_ratio  NUMERIC,                       -- PCR by Premium
  writers_zone            TEXT,                          -- "BULLISH" | "NEUTRAL" | "BEARISH"
  writers_confidence      NUMERIC,                       -- 0.0-1.0 confidence score
  max_pain                NUMERIC,                       -- Max Pain strike price
  max_ce_oi_strike        NUMERIC,                       -- Strike with highest CE OI
  max_pe_oi_strike        NUMERIC,                       -- Strike with highest PE OI
  gamma_exposure          JSONB,                         -- {regime, flipLevel, netGEX} from GEX calc
  iv_skew                 JSONB,                         -- {skew, bias, call_iv, put_iv}

  -- ── Price Action & Patterns ───────────────────────────────
  poc_distance            NUMERIC,                       -- LTP distance from Volume POC
  price_action_score      NUMERIC,                       -- SMC score: -2 to +2
  pa_type                 TEXT,                          -- "Breakout"|"Breakdown"|"Trending"|"Ranging"
  candle_pattern          TEXT,                          -- Last detected candle pattern(s)
  aroon_up                NUMERIC,                       -- Aroon Up (0-100)
  aroon_down              NUMERIC,                       -- Aroon Down (0-100)
  vwap_status             TEXT,                          -- "Above" | "Below"

  -- ── Market Composite ─────────────────────────────────────
  market_strength         NUMERIC,                       -- Composite 0-100 strength score
  orb_range               JSONB,                         -- {high, low} Opening Range Breakout

  -- ── Data Quality ─────────────────────────────────────────
  candle_count            INTEGER,                       -- Total candles in history
  today_candle_count      INTEGER,                       -- Today's candle count

  -- ── Debug ────────────────────────────────────────────────
  debug_flags             TEXT,                          -- Comma-separated debug flags

  -- ── ML Training Label (filled after trade outcome) ───────
  label                   INTEGER,                       -- 0=BUY_CE, 1=BUY_PE, 2=WAIT
  label_source            TEXT                           -- "manual" | "outcome" | "auto"
);

-- =============================================
-- TABLE 2: active_exit_orders
-- Replaces Google Sheets "Active_Exit_Orders" tab
-- Tracks SL and Target orders for each trade
-- =============================================
CREATE TABLE IF NOT EXISTS active_exit_orders (
  id                      UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
  entry_order_id          TEXT          NOT NULL UNIQUE,
  sl_order_id             TEXT,
  target_order_id         TEXT,
  symbol                  TEXT          NOT NULL,
  entry_price             NUMERIC(10,2),
  sl_price                NUMERIC(10,2),
  target_price            NUMERIC(10,2),
  quantity                INTEGER,
  timestamp               TIMESTAMPTZ   DEFAULT NOW(),
  status                  TEXT          DEFAULT 'ACTIVE',
  risk_reward_ratio       NUMERIC(6,2),

  -- Exit Details
  exit_type               TEXT,
  exit_price              NUMERIC(10,2),
  pnl                     NUMERIC(12,2),
  exit_timestamp          TIMESTAMPTZ,

  -- Institutional Metadata
  security_id             TEXT,
  max_loss                NUMERIC(12,2),
  max_profit              NUMERIC(12,2),
  actual_rr               NUMERIC(8,2),
  execution_time          TEXT,

  created_at              TIMESTAMPTZ   DEFAULT NOW()
);

-- =============================================
-- TABLE 3: trades
-- Replaces Google Sheets "Trades" tab
-- Complete trade lifecycle tracking
-- =============================================
CREATE TABLE IF NOT EXISTS trades (
  id                      UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
  entry_order_id          TEXT          NOT NULL UNIQUE,
  timestamp               TIMESTAMPTZ   DEFAULT NOW(),
  symbol                  TEXT          NOT NULL,
  entry_price             NUMERIC(10,2),
  stop_loss               NUMERIC(10,2),
  target                  NUMERIC(10,2),
  quantity                INTEGER,
  status                  TEXT          DEFAULT 'ACTIVE',
  signal                  TEXT,
  confidence              NUMERIC(10,4),
  risk_reward_ratio       NUMERIC(6,2),

  -- Exit Results
  exit_price              NUMERIC(10,2),
  pnl                     NUMERIC(12,2),
  exit_type               TEXT,
  exit_timestamp          TIMESTAMPTZ,

  -- Performance Metrics
  max_loss                NUMERIC(12,2),
  max_profit              NUMERIC(12,2),
  actual_rr               NUMERIC(8,2),

  created_at              TIMESTAMPTZ   DEFAULT NOW()
);

-- =============================================
-- INDEXES for fast lookups
-- Active Exit Orders: the monitor queries this every 2 minutes
CREATE INDEX IF NOT EXISTS idx_exit_orders_status ON active_exit_orders(status);
CREATE INDEX IF NOT EXISTS idx_exit_orders_entry_id ON active_exit_orders(entry_order_id);

-- Trades: query by status and lookup by entry_order_id
CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_entry_id ON trades(entry_order_id);
CREATE INDEX IF NOT EXISTS idx_trades_timestamp ON trades(timestamp DESC);

-- =============================================
-- ROW LEVEL SECURITY (RLS)
-- Enable RLS but allow service_role full access
-- =============================================
ALTER TABLE signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE active_exit_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;

-- Allow service_role (used by n8n) to do everything
CREATE POLICY "Service role full access on signals" ON signals
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access on active_exit_orders" ON active_exit_orders
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access on trades" ON trades
  FOR ALL USING (true) WITH CHECK (true);

-- =============================================
-- USEFUL VIEWS for AI Model Training
-- =============================================

-- View: Get all completed trades with P&L
CREATE OR REPLACE VIEW completed_trades_summary AS
SELECT 
  t.entry_order_id,
  t.symbol,
  t.signal,
  t.entry_price,
  t.exit_price,
  t.pnl,
  t.exit_type,
  t.confidence,
  t.risk_reward_ratio,
  t.timestamp AS entry_time,
  t.exit_timestamp AS exit_time,
  EXTRACT(EPOCH FROM (t.exit_timestamp - t.timestamp)) / 60 AS duration_minutes
FROM trades t
WHERE t.status = 'CLOSED'
ORDER BY t.timestamp DESC;

-- View: Daily P&L summary
CREATE OR REPLACE VIEW daily_pnl_summary AS
SELECT 
  DATE(timestamp) AS trade_date,
  COUNT(*) AS total_trades,
  SUM(CASE WHEN pnl > 0 THEN 1 ELSE 0 END) AS winning_trades,
  SUM(CASE WHEN pnl <= 0 THEN 1 ELSE 0 END) AS losing_trades,
  ROUND(SUM(pnl)::NUMERIC, 2) AS total_pnl,
  ROUND(AVG(pnl)::NUMERIC, 2) AS avg_pnl,
  ROUND(MAX(pnl)::NUMERIC, 2) AS best_trade,
  ROUND(MIN(pnl)::NUMERIC, 2) AS worst_trade
FROM trades
WHERE status = 'CLOSED'
GROUP BY DATE(timestamp)
ORDER BY trade_date DESC;

-- View: Signal accuracy analysis (for model tuning)
CREATE OR REPLACE VIEW signal_accuracy AS
SELECT 
  s.signal,
  COUNT(*) AS total_signals,
  ROUND(AVG(s.confidence)::NUMERIC, 4) AS avg_confidence,
  ROUND(AVG(s.rsi)::NUMERIC, 2) AS avg_rsi,
  ROUND(AVG(s.vix)::NUMERIC, 2) AS avg_vix,
  ROUND(AVG(s.market_strength)::NUMERIC, 2) AS avg_market_strength
FROM signals s
GROUP BY s.signal
ORDER BY total_signals DESC;
