/**
 * TRADING DATA HOOK
 * 
 * Central state management for live trading data. 
 * Orchestrates polling from Google Sheets and live engine health diagnostics.
 */

import { useState, useEffect, useCallback, useRef } from 'react';
import {
    fetchSignals, fetchActiveTrades, fetchTradeSummary, fetchMarketData,
    computeTradeStats, fetchEngineHealth,
    type LiveSignal, type ActiveTrade, type TradeSummary,
    type MarketSnapshot, type TradeStats, type EngineHealth
} from '../services/supabaseApi';

/**
 * Unified state object for the Zenith Trading Terminal.
 * Contains everything from live signals to engine health diagnostics.
 */
export interface TradingState {
    /** Most recent signals generated by the Python Engine (Limit 100) */
    signals: LiveSignal[];        
    /** Currently active positions (extracted from active_exit_orders table) */
    activeTrades: ActiveTrade[];  
    /** Historical ledger of all completed trades */
    tradeSummary: TradeSummary[]; 
    /** Real-time market data (Nifty LTP, India VIX, Market Status) */
    marketData: MarketSnapshot | null; 
    /** Aggregated performance metrics (Win Rate, Total PnL, Profit Factor) */
    stats: TradeStats | null;      
    /** Real-time operational health of the remote Python Engine cluster */
    engineHealth: EngineHealth | null; 
    /** UI loading state (true during fetch cycles) */
    loading: boolean;             
    /** Error message string, null if system is healthy */
    error: string | null;         
    /** Timestamp of the last successful data synchronization */
    lastRefresh: Date | null;     
    /** Reflects if the Indian Market is currently in active session */
    isLive: boolean;              
    /** Function to force an immediate system-wide data refresh */
    refresh: () => void;          
    /** True if the user has manually paused the auto-polling cycle */
    isPaused: boolean;            
    /** Toggle function for the auto-polling mechanism */
    togglePolling: () => void;    
}

/**
 * THE BRAIN OF THE FRONTEND: useTrading
 * 
 * This hook acts as the primary data orchestrator for the entire application.
 * It manages a complex polling cycle that dynamically adjusts its frequency 
 * based on Indian Market Hours (IST):
 * 
 * - DURING MARKET (09:15 - 15:30 IST): Polls every 30 seconds for maximum responsiveness.
 * - AFTER HOURS: Polls every 180 seconds to conserve resources while maintaining state.
 * 
 * It uses a Promise.allSettled pattern to ensure that if one data source (like Engine Health)
 * is down, the rest of the UI (like Signals) continues to function.
 */
export function useTrading(): TradingState {
    const [signals, setSignals] = useState<LiveSignal[]>([]);
    const [activeTrades, setActiveTrades] = useState<ActiveTrade[]>([]);
    const [tradeSummary, setTradeSummary] = useState<TradeSummary[]>([]);
    const [marketData, setMarketData] = useState<MarketSnapshot | null>(null);
    const [stats, setStats] = useState<TradeStats | null>(null);
    const [engineHealth, setEngineHealth] = useState<EngineHealth | null>(null);
    const [loading, setLoading] = useState(true);
    const [isPaused, setIsPaused] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [lastRefresh, setLastRefresh] = useState<Date | null>(null);
    const timerRef = useRef<ReturnType<typeof setTimeout>>();

    /**
     * CORE SYNC FUNCTION
     * Orchestrates heavy data fetching across multiple Supabase tables and external APIs.
     */
    const load = useCallback(async () => {
        try {
            setLoading(true);
            setError(null);

            // Fetch primary trade data in parallel
            const [sigsResult, tradesResult, summaryResult] = await Promise.allSettled([
                fetchSignals(5000),
                fetchActiveTrades(),
                fetchTradeSummary(),
            ]);

            let latestSignals: LiveSignal[] = [];
            if (sigsResult.status === 'fulfilled') {
                latestSignals = sigsResult.value;
                setSignals(latestSignals);
            }
            if (tradesResult.status === 'fulfilled') setActiveTrades(tradesResult.value);
            if (summaryResult.status === 'fulfilled') {
                setTradeSummary(summaryResult.value);
                setStats(computeTradeStats(summaryResult.value));
            }

            // Fetch secondary telemetry (Health & Market Snapshots)
            try {
                const [market, health] = await Promise.all([
                    fetchMarketData(latestSignals[0]),
                    fetchEngineHealth()
                ]);
                setMarketData(market);
                setEngineHealth(health);
            } catch (mErr) {
                console.warn('Market/Health diagnostics cycle failed', mErr);
            }

            setLastRefresh(new Date());
        } catch (e: unknown) {
            setError(e instanceof Error ? e.message : 'Critical sync error occurred');
        } finally {
            setLoading(false);
        }
    }, []);

    /**
     * DYNAMIC POLLING SCHEDULER
     * Calculates IST current time to determine if market is open.
     */
    const scheduleNext = useCallback(() => {
        clearTimeout(timerRef.current);
        if (isPaused) return;

        const now = new Date();
        // Indian Standard Time offset calculation (+5:30)
        const istMin = (now.getUTCHours() * 60 + now.getUTCMinutes() + 330);
        
        // 09:15 IST = 555 mins | 15:30 IST = 930 mins
        const marketOpen = istMin >= 555 && istMin <= 930;
        const interval = marketOpen ? 30_000 : 180_000; // 30s vs 3m

        timerRef.current = setTimeout(() => { load(); scheduleNext(); }, interval);
    }, [load, isPaused]);

    useEffect(() => {
        load();
        scheduleNext();
        return () => clearTimeout(timerRef.current);
    }, [load, scheduleNext]);

    const togglePolling = useCallback(() => {
        setIsPaused(prev => !prev);
    }, []);

    return {
        signals, activeTrades, tradeSummary,
        marketData, stats, engineHealth,
        loading, error, lastRefresh,
        isLive: !!marketData?.marketOpen,
        refresh: load,
        isPaused,
        togglePolling
    };
}
